trainingInput:
  masterConfig:
    containerCommand: [
        "/bin/bash",
        "-c",
        "python -u -m dnntrain --epochs=10 --input-dir=gs://desposito-noisefilter/dataset.tar.gz --output-dir=gs://desposito-noisefilter --experiment-name=dnn-train-time-decay1e-6-lr1e-4-w60-batch256 --overload-settings=gs://desposito-noisefilter/overload_settings.json"
    ]