trainingInput:
  masterConfig:
    containerCommand: [
        "/bin/bash",
        "-c",
        "python -u -m dnntrain --epochs=10 --input-dir=gs://desposito-noisefilter/dataset.tar.gz --output-dir=gs://desposito-noisefilter --experiment-name=dnn-train-time-decay1e-4-lr1e-3-w60-batch512-no-silent --overload-settings=gs://desposito-noisefilter/overload_settings.json"
    ]